version: "3.8"
services:
    bot:
        build: .
        stop_signal: SIGINT
        restart: unless-stopped
        volumes:
            - ".env:/app/.env"
            # Если хотите переопределить локализацию, подложите нужный каталог
            # - "/your/path/to/locales:/app/bot/locales"
            # Или даже так:
            # - "/your/custom/language:/app/bot/locales/ru"
